# Generated by Django 6.0.5 on 2026-05-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='reputation_rating',
        ),
    ]
