# Generated by Django 6.0.5 on 2026-05-27 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0003_rename_category_categorymodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarterDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_deals', to=settings.AUTH_USER_MODEL)),
                ('initiator_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_initiator', to='offers.offermodel')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_deals', to=settings.AUTH_USER_MODEL)),
                ('responder_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals_as_responder', to='offers.offermodel')),
            ],
        ),
    ]
