# Generated by Django 6.0.5 on 2026-05-27 17:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('offers', '0003_rename_category_categorymodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarterDeal',
            new_name='OfferDealModel',
        ),
    ]
